const GET_DOMAIN_DATA = 'BO_DOMAIN_SERVICES_PANE/GET_DOMAIN_DATA';
const GET_TRANSFER_DOMAIN_DATA = 'BO_DOMAIN_SERVICES_PANE/GET_TRANSFER_DOMAIN_DATA';
const GET_DOMAIN_REGISTRY_DATA = 'BO_DOMAIN_SERVICES_PANE/GET_DOMAIN_REGISTRY_DATA';
const GET_PREMIUM_DOMAIN_DATA = 'BO_DOMAIN_SERVICES_PANE/GET_PREMIUM_DOMAIN_DATA';
const GOT_DATA_FROM_SERVER = 'BO_DOMAIN_SERVICES_PANE/GOT_DATA_FROM_SERVER';
const SHOW_LOADER = 'BO_DOMAIN_SERVICES_PANE/SHOW_LOADER';
const CLOSE_LOADER = 'BO_DOMAIN_SERVICES_PANE/CLOSE_LOADER';

export default {
  GET_DOMAIN_DATA,
  GET_TRANSFER_DOMAIN_DATA,
  GET_DOMAIN_REGISTRY_DATA,
  GET_PREMIUM_DOMAIN_DATA,
  GOT_DATA_FROM_SERVER,
  SHOW_LOADER,
  CLOSE_LOADER
};